from enum import Enum
from typing import List, Optional, Literal, Dict, Any
from pydantic import BaseModel, Field, FieldValidationInfo, field_validator


class ClassificationType(str, Enum):
    ANSWERABLE = "answerable"
    REQUIRES_CLARIFICATION = "requires_clarification"
    REQUIRES_ESCALATION = "requires_escalation"
    OUT_OF_SCOPE = "out_of_scope"
    SAFE_FAILURE = "safe_failure"


class SourceItem(BaseModel):
    source_id: str = Field(..., description="Knowledge-base document ID or resolved-case ID")
    passage: str = Field(..., min_length=1, description="Relevant excerpt or stable passage identifier")


class FinalOutput(BaseModel):
    classification: ClassificationType = Field(..., description="Classification route of the response")
    answer: str = Field(..., min_length=1, description="Final response answer text")
    sources: List[SourceItem] = Field(default_factory=list, description="List of cited sources")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score between 0.0 and 1.0")
    requires_human: bool = Field(..., description="Whether human agent escalation is required")
    reason: str = Field(..., min_length=1, description="Brief explanation of the route and confidence")
    clarification_question: Optional[str] = Field(default=None, description="Clarification question if required")
    warnings: List[str] = Field(default_factory=list, description="Warning messages if any")


class AgentState(BaseModel):
    question: str = Field(..., description="Original user prompt or question")
    classification: Optional[ClassificationType] = Field(default=None, description="Classified intent of the question")
    retrieved_docs: List[Dict[str, Any]] = Field(default_factory=list, description="Retrieved context documents and cases")
    draft_answer: Optional[str] = Field(default=None, description="Draft response generated by local LLM")
    verification_attempts: int = Field(default=0, ge=0, description="Count of schema/guardrail verification attempts")
    final_output: Optional[FinalOutput] = Field(default=None, description="Validated response matching output_schema.json")
